export {default as Header} from './Header.jsx'
export {default as Slider} from './Slider.jsx'
export {default as MiddleText} from './MiddleText.jsx'
export{default as AddToCartButton} from './AddToCartButton'
export {default as MobileMenu} from './MobileMenu'
